config/routes.rb
MyGists::Application.routes.draw do
  get "gists/search"
  resources :gists
  root 'gists#index'

end

app/models/gist.rb
class Gist < ActiveRecord::Base

  def self.search(search)
    if search
      find(:all, :conditions => ['lang LIKE ?', "%#{search}%"])
    else
      limit(0)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
    @gists = Gist.paginate(:page => params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def search
    @gists = Gist.search(params[:lang])
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>

  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :snippet %><br>
    <%= f.text_area :snippet, style:"width: 100%; height: 200px;" %>
  </div>
  <div class="field">
    <%= f.label :lang %><br>
    <%= f.select :lang, Pygments.lexers.keys.sort.map! {|l| l.downcase.strip}, {}, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class:"btn btn-default" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-success" do %>

    <% end %>
  </div>
<% end %>

app/views/gists/edit.html.erb
<div class="row">
  <div class="col-xs-8">
    <h1>Editing gist nr <%= @gist.id %></h1>
    Language: <div class="badge alert-success"><%= @gist.lang %></div>
  </div>
  <div class="col-xs-4">
    <div class="pull-right">
      <%= link_to gists_path, class:"btn btn-danger" do %>
          <i class="icon-backward"></i> Back
      <% end %>

      <%= link_to gist_path(@gist), class:"btn btn-info" do %>
          <i class="icon-book-open"></i> Show
      <% end %>
    </div>
  </div>
</div>

<hr/>

<%= render 'form' %>

app/views/gists/index.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Listing gists</h1>
  </div>
  <div class="col-xs-6">
      <div class="pull-right">
        <%= link_to new_gist_path, class: "btn btn-success" do %>
            <i class="icon-plus"></i> Create New
        <% end %>
      </div>
  </div>
</div>


<div class="text-center">
    <%= will_paginate %>
</div>

<table class="table table-bordered table-hover table-responsive">
  <thead>
    <tr>
      <th class="text-center">#</th>
      <th class="hidden-xs">Snippet</th>
      <th>Lang</th>
      <th class="hidden-xs">Description</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @gists.each do |gist| %>
      <tr>
        <td class="text-center"><%= gist.id %></td>
        <td class="hidden-xs">
            <%= raw Pygments.highlight(gist.snippet, lexer: gist.lang) %>
        </td>
        <td><%= gist.lang %></td>
        <td class="hidden-xs"><%= gist.description %></td>


        <td class="text-center">
          <%= link_to gist, class: "btn btn-info " do %>
              <i class="icon-book-open"></i>
          <% end %>
        </td>
        <td class="text-center">
          <%= link_to edit_gist_path(gist), class: "btn btn-success" do %>
              <i class="icon-edit"></i>
          <% end %>
        </td>
        <td class="text-center">
          <%= link_to gist, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
              <i class="icon-folder-delete"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="infinite-scrolling">
  <%= will_paginate %>
</div>

<br>

app/views/gists/new.html.erb
<div class="row">
  <div class="col-xs-8">
    <h1>New gist</h1>
  </div>
  <div class="col-xs-4">
    <div class="pull-right">
      <%= link_to gists_path, class:"btn btn-danger" do %>
          <i class="icon-backward"></i> Back
      <% end %>
    </div>
  </div>
</div>

<hr/>
<%= render 'form' %>

app/views/gists/search.html.erb
<% if(@gists.length > 0) %>
    <h2>Results</h2>
    <hr/>

    <table class="table table-bordered table-hover table-responsive">
      <thead>
      <tr>
        <th class="text-center">#</th>
        <th>Snippet</th>
        <th>Lang</th>
        <th>Description</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      </thead>

      <tbody>
      <% @gists.each do |gist| %>
          <tr>
            <td class="text-center"><%= gist.id %></td>
            <td>
              <div class="well"><%= gist.snippet[0,10] %>...</div>
            </td>
            <td><%= gist.lang %></td>
            <td><%= gist.description %></td>


            <td class="text-center">
              <%= link_to gist, class: "btn btn-info " do %>
                  <i class="icon-book-open"></i>
              <% end %>
            </td>
            <td class="text-center">
              <%= link_to edit_gist_path(gist), class: "btn btn-success" do %>
                  <i class="icon-edit"></i>
              <% end %>
            </td>
            <td class="text-center">
              <%= link_to gist, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
                  <i class="icon-folder-delete"></i>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% else if(@gists.length == 0) %>
    <div class="alert alert-info">
      <strong>No gists found.</strong>
    </div>
<% end end %>

app/views/gists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-8">
    <h1>Details of Gist nr <%= @gist.id %></h1>
    Language: <div class="badge alert-success"><%= @gist.lang %></div>
  </div>
    <div class="col-xs-4">
      <div class="pull-right">
        <%= link_to gists_path, class:"btn btn-danger" do %>
            <i class="icon-backward"></i> Back
        <% end %>

        <%= link_to edit_gist_path(@gist), class:"btn btn-success" do %>
            <i class="icon-edit"></i> Edit
        <% end %>
      </div>
    </div>
</div>

<hr/>

  <h4>Code:</h4>


<div class="alert-danger" id="code">
    <%= raw Pygments.highlight(@gist.snippet, lexer: @gist.lang) %>
</div>


  <h4>Description:</h4>
  <div class="alert alert-info">
    <%= @gist.description %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGists</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Gist Agregator", "/", :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(gists_path) || current_page?(root_path) %>">
          <%= link_to gists_path do %>
              <i class="icon-list"></i> All gists
          <% end %>
        </li>
        <li class="<%= 'active' if current_page?(new_gist_path) %>">
          <%= link_to new_gist_path do %>
              <i class="icon-plus"></i> Create New
          <% end %>
        </li>
      </ul>
      <form class="navbar-form navbar-left pull-right" role="search" action="/gists/search">
        <div class="form-group">
          <%= select_tag(:lang, options_for_select(Pygments.lexers.keys.sort.map! {|l| l.downcase.strip}, params[:lang]))%>
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
    </div>
  </div>
</div>
<div class="row">
    <div class="container">
        <%= yield %>
    </div>
</div>
</body>
</html>